import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, act } from '@testing-library/react';
import '@testing-library/jest-dom';
import ContentEditor from '@/components/admin/ContentEditor';
import type { ContentItem } from '@/types';

// Mock LanguageProvider
vi.mock('@/components/providers/LanguageProvider', () => ({
  useLanguage: () => ({
    locale: 'tr' as const,
    setLocale: vi.fn(),
    t: (key: string) => {
      const map: Record<string, string> = {
        'admin.contentEditor': 'İçerik Düzenleyici',
        'admin.newContent': 'Yeni İçerik',
        'admin.editContent': 'İçerik Düzenle',
        'admin.contentType': 'İçerik Türü',
        'admin.slug': 'Slug',
        'admin.slugAutoGenerated': 'TR başlığından otomatik üretilir',
        'admin.slugPreserved': 'Düzenleme modunda slug korunur',
        'admin.coverImage': 'Kapak Görseli',
        'admin.coverImagePlaceholder': 'Görsel URL\'si girin',
        'admin.trContent': 'TR İçerik',
        'admin.enContent': 'EN İçerik',
        'admin.trSeo': 'TR SEO',
        'admin.enSeo': 'EN SEO',
        'admin.titleField': 'Başlık',
        'admin.summaryField': 'Özet',
        'admin.seoTitle': 'SEO Başlık',
        'admin.seoDescription': 'SEO Açıklama',
        'admin.save': 'Kaydet',
        'admin.status': 'Durum',
        'admin.statusDraft': 'Taslak',
        'admin.statusPublished': 'Yayında',
        'admin.statusUnpublished': 'Yayından Kaldırılmış',
      };
      return map[key] ?? key;
    },
  }),
}));

// Mock slug
vi.mock('@/lib/slug', () => ({
  generateSlug: (title: string) =>
    title
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, ''),
}));

function makeItem(overrides: Partial<ContentItem> = {}): ContentItem {
  return {
    id: 'test-001',
    slug: 'istanbul',
    type: 'location',
    status: 'published',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
    coverImage: '/images/istanbul.jpg',
    seo: {
      tr: { title: 'İstanbul SEO', description: 'İstanbul açıklama' },
      en: { title: 'Istanbul SEO', description: 'Istanbul description' },
    },
    content: {
      tr: { title: 'İstanbul', summary: 'Harika şehir' },
      en: { title: 'Istanbul', summary: 'Great city' },
    },
    ...overrides,
  };
}

describe('ContentEditor', () => {
  let onSave: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    onSave = vi.fn();
  });

  it('oluşturma modunda "Yeni İçerik" başlığı gösterir', () => {
    render(<ContentEditor onSave={onSave} contentType="location" />);
    expect(screen.getByText('Yeni İçerik')).toBeInTheDocument();
  });

  it('düzenleme modunda "İçerik Düzenle" başlığı gösterir', () => {
    render(<ContentEditor item={makeItem()} onSave={onSave} contentType="location" />);
    expect(screen.getByText('İçerik Düzenle')).toBeInTheDocument();
  });

  it('içerik türünü readonly olarak gösterir', () => {
    render(<ContentEditor onSave={onSave} contentType="blog" />);
    expect(screen.getByText('Blog')).toBeInTheDocument();
  });

  it('durum seçici Draft/Published/Unpublished seçeneklerini içerir', () => {
    render(<ContentEditor onSave={onSave} contentType="location" />);
    const select = screen.getByDisplayValue('Taslak');
    expect(select).toBeInTheDocument();
    expect(select.querySelectorAll('option')).toHaveLength(3);
  });

  it('oluşturma modunda TR başlığından slug otomatik üretir', async () => {
    render(<ContentEditor onSave={onSave} contentType="location" />);

    // TR content tab is active by default — find title input by label
    const labels = screen.getAllByText('Başlık');
    const titleLabel = labels[0];
    const titleInput = titleLabel.closest('div')!.querySelector('input')!;

    await act(async () => {
      fireEvent.change(titleInput, { target: { value: 'Test Başlık' } });
    });

    // Kaydet'e tıkla ve slug'ın otomatik üretildiğini doğrula
    fireEvent.click(screen.getByText('Kaydet'));
    const saved = onSave.mock.calls[0][0] as ContentItem;
    expect(saved.slug).toBe('test-ba-l-k');
  });

  it('düzenleme modunda slug alanı readonly olur', () => {
    render(<ContentEditor item={makeItem()} onSave={onSave} contentType="location" />);
    const slugInput = screen.getByDisplayValue('istanbul');
    expect(slugInput).toHaveAttribute('readOnly');
  });

  it('düzenleme modunda mevcut değerleri doldurur', () => {
    const item = makeItem();
    render(<ContentEditor item={item} onSave={onSave} contentType="location" />);
    expect(screen.getByDisplayValue('istanbul')).toBeInTheDocument();
    expect(screen.getByDisplayValue('/images/istanbul.jpg')).toBeInTheDocument();
    expect(screen.getByDisplayValue('İstanbul')).toBeInTheDocument();
  });

  it('tab geçişi ile EN içerik alanlarını gösterir', () => {
    const item = makeItem();
    render(<ContentEditor item={item} onSave={onSave} contentType="location" />);

    fireEvent.click(screen.getByText('EN İçerik'));
    expect(screen.getByDisplayValue('Istanbul')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Great city')).toBeInTheDocument();
  });

  it('SEO TR tab ile SEO alanlarını gösterir', () => {
    const item = makeItem();
    render(<ContentEditor item={item} onSave={onSave} contentType="location" />);

    fireEvent.click(screen.getByText('TR SEO'));
    expect(screen.getByDisplayValue('İstanbul SEO')).toBeInTheDocument();
    expect(screen.getByDisplayValue('İstanbul açıklama')).toBeInTheDocument();
  });

  it('SEO EN tab ile İngilizce SEO alanlarını gösterir', () => {
    const item = makeItem();
    render(<ContentEditor item={item} onSave={onSave} contentType="location" />);

    fireEvent.click(screen.getByText('EN SEO'));
    expect(screen.getByDisplayValue('Istanbul SEO')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Istanbul description')).toBeInTheDocument();
  });

  it('kaydet butonuna tıklayınca onSave çağrılır', () => {
    const item = makeItem();
    render(<ContentEditor item={item} onSave={onSave} contentType="location" />);

    fireEvent.click(screen.getByText('Kaydet'));
    expect(onSave).toHaveBeenCalledTimes(1);

    const saved = onSave.mock.calls[0][0] as ContentItem;
    expect(saved.slug).toBe('istanbul');
    expect(saved.type).toBe('location');
    expect(saved.content.tr.title).toBe('İstanbul');
    expect(saved.seo.tr.title).toBe('İstanbul SEO');
  });

  it('düzenleme modunda slug korunur (değişmez)', () => {
    const item = makeItem({ slug: 'original-slug' });
    render(<ContentEditor item={item} onSave={onSave} contentType="location" />);

    // TR title değiştir
    const titleInput = screen.getByDisplayValue('İstanbul');
    fireEvent.change(titleInput, { target: { value: 'Yeni Başlık' } });

    fireEvent.click(screen.getByText('Kaydet'));
    const saved = onSave.mock.calls[0][0] as ContentItem;
    expect(saved.slug).toBe('original-slug');
  });

  it('varsayılan durum draft olarak ayarlanır (oluşturma modu)', () => {
    render(<ContentEditor onSave={onSave} contentType="blog" />);
    const select = screen.getByDisplayValue('Taslak') as HTMLSelectElement;
    expect(select.value).toBe('draft');
  });

  it('durum değiştirilebilir', () => {
    render(<ContentEditor onSave={onSave} contentType="blog" />);
    const select = screen.getByDisplayValue('Taslak');
    fireEvent.change(select, { target: { value: 'published' } });

    fireEvent.click(screen.getByText('Kaydet'));
    const saved = onSave.mock.calls[0][0] as ContentItem;
    expect(saved.status).toBe('published');
  });
});
