import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, act } from '@testing-library/react';
import '@testing-library/jest-dom';
import FriendExperienceEditor from '@/components/admin/FriendExperienceEditor';
import type { ContentItem, FriendExperienceContent } from '@/types';

// Mock LanguageProvider
vi.mock('@/components/providers/LanguageProvider', () => ({
  useLanguage: () => ({
    locale: 'tr' as const,
    setLocale: vi.fn(),
    t: (key: string) => {
      const map: Record<string, string> = {
        'admin.newContent': 'Yeni İçerik',
        'admin.editContent': 'İçerik Düzenle',
        'admin.friendName': 'Arkadaş Adı',
        'admin.narrative': 'Kişisel Anlatım',
        'admin.visitedLocations': 'Ziyaret Edilen Yerler',
        'admin.locationComments': 'Lokasyon Yorumları',
        'admin.gallery': 'Fotoğraf Galerisi',
        'admin.addLocation': 'Yer Ekle',
        'admin.addComment': 'Yorum Ekle',
        'admin.addImage': 'Görsel Ekle',
        'admin.locationName': 'Yer Adı',
        'admin.comment': 'Yorum',
        'admin.imageUrl': 'Görsel URL',
        'admin.status': 'Durum',
        'admin.statusDraft': 'Taslak',
        'admin.statusPublished': 'Yayında',
        'admin.statusUnpublished': 'Yayından Kaldırılmış',
        'admin.slug': 'Slug',
        'admin.slugAutoGenerated': 'Otomatik üretilir',
        'admin.slugPreserved': 'Slug korunur',
        'admin.coverImage': 'Kapak Görseli',
        'admin.coverImagePlaceholder': 'Görsel URL girin',
        'admin.trContent': 'TR İçerik',
        'admin.enContent': 'EN İçerik',
        'admin.trSeo': 'TR SEO',
        'admin.enSeo': 'EN SEO',
        'admin.titleField': 'Başlık',
        'admin.summaryField': 'Özet',
        'admin.seoTitle': 'SEO Başlık',
        'admin.seoDescription': 'SEO Açıklama',
        'admin.save': 'Kaydet',
      };
      return map[key] ?? key;
    },
  }),
}));

vi.mock('@/lib/slug', () => ({
  generateSlug: (title: string) =>
    title.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, ''),
}));

function makeExperience(overrides: Partial<ContentItem> = {}): ContentItem {
  const trContent: FriendExperienceContent = {
    title: 'Ali İstanbul Gezisi',
    summary: 'Harika bir deneyim',
    friendName: 'Ali',
    visitedLocations: [{ name: 'İstanbul', slug: 'istanbul' }],
    narrative: 'Çok güzel bir gezi oldu.',
    locationComments: [{ locationName: 'Ayasofya', comment: 'Muhteşem' }],
    gallery: ['/images/ali-1.jpg'],
  };
  const enContent: FriendExperienceContent = {
    title: 'Ali Istanbul Trip',
    summary: 'Great experience',
    friendName: 'Ali',
    visitedLocations: [{ name: 'Istanbul', slug: 'istanbul' }],
    narrative: 'It was a wonderful trip.',
    locationComments: [{ locationName: 'Hagia Sophia', comment: 'Magnificent' }],
    gallery: ['/images/ali-1.jpg'],
  };
  return {
    id: 'fe-001',
    slug: 'ali-istanbul',
    type: 'friend-experience',
    status: 'published',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
    coverImage: '/images/ali-cover.jpg',
    seo: {
      tr: { title: 'Ali İstanbul SEO', description: 'Ali deneyimi' },
      en: { title: 'Ali Istanbul SEO', description: 'Ali experience' },
    },
    content: { tr: trContent, en: enContent },
    ...overrides,
  };
}

describe('FriendExperienceEditor', () => {
  let onSave: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    onSave = vi.fn();
  });

  it('oluşturma modunda boş alanlarla render eder', () => {
    render(<FriendExperienceEditor onSave={onSave} />);
    expect(screen.getByText('Yeni İçerik')).toBeInTheDocument();
    expect(screen.getByText('Arkadaş Adı')).toBeInTheDocument();
    expect(screen.getByText('Kişisel Anlatım')).toBeInTheDocument();
    expect(screen.getByText('Ziyaret Edilen Yerler')).toBeInTheDocument();
    expect(screen.getByText('Lokasyon Yorumları')).toBeInTheDocument();
    expect(screen.getByText('Fotoğraf Galerisi')).toBeInTheDocument();
  });

  it('düzenleme modunda mevcut verileri doldurur', () => {
    const exp = makeExperience();
    render(<FriendExperienceEditor experience={exp} onSave={onSave} />);
    expect(screen.getByText('İçerik Düzenle')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Ali')).toBeInTheDocument();
    expect(screen.getByDisplayValue('ali-istanbul')).toBeInTheDocument();
    expect(screen.getByDisplayValue('/images/ali-cover.jpg')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Çok güzel bir gezi oldu.')).toBeInTheDocument();
  });

  it('arkadaş adı input alanı çalışır', async () => {
    render(<FriendExperienceEditor onSave={onSave} />);
    const friendLabel = screen.getByText('Arkadaş Adı');
    const friendInput = friendLabel.closest('div')!.querySelector('input')!;

    await act(async () => {
      fireEvent.change(friendInput, { target: { value: 'Mehmet' } });
    });

    fireEvent.click(screen.getByText('Kaydet'));
    const saved = onSave.mock.calls[0][0] as ContentItem;
    const content = saved.content.tr as FriendExperienceContent;
    expect(content.friendName).toBe('Mehmet');
  });

  it('kaydet butonuna tıklayınca doğru ContentItem yapısı ile onSave çağrılır', () => {
    const exp = makeExperience();
    render(<FriendExperienceEditor experience={exp} onSave={onSave} />);

    fireEvent.click(screen.getByText('Kaydet'));
    expect(onSave).toHaveBeenCalledTimes(1);

    const saved = onSave.mock.calls[0][0] as ContentItem;
    expect(saved.type).toBe('friend-experience');
    expect(saved.slug).toBe('ali-istanbul');
    expect(saved.seo.tr.title).toBe('Ali İstanbul SEO');

    const trContent = saved.content.tr as FriendExperienceContent;
    expect(trContent.friendName).toBe('Ali');
    expect(trContent.narrative).toBe('Çok güzel bir gezi oldu.');
    expect(trContent.visitedLocations).toHaveLength(1);
    expect(trContent.locationComments).toHaveLength(1);
    expect(trContent.gallery).toHaveLength(1);
  });

  it('ziyaret edilen yer eklenebilir', () => {
    render(<FriendExperienceEditor onSave={onSave} />);

    fireEvent.click(screen.getByText('+ Yer Ekle'));

    // Yeni eklenen boş location input'u olmalı
    const locationInputs = screen.getAllByPlaceholderText('Yer Adı');
    expect(locationInputs).toHaveLength(1);

    fireEvent.change(locationInputs[0], { target: { value: 'Kapadokya' } });
    fireEvent.click(screen.getByText('Kaydet'));

    const saved = onSave.mock.calls[0][0] as ContentItem;
    const trContent = saved.content.tr as FriendExperienceContent;
    expect(trContent.visitedLocations).toHaveLength(1);
    expect(trContent.visitedLocations[0].name).toBe('Kapadokya');
  });

  it('durum değiştirilebilir', () => {
    render(<FriendExperienceEditor onSave={onSave} />);
    const select = screen.getByDisplayValue('Taslak');
    fireEvent.change(select, { target: { value: 'published' } });

    fireEvent.click(screen.getByText('Kaydet'));
    const saved = onSave.mock.calls[0][0] as ContentItem;
    expect(saved.status).toBe('published');
  });

  it('galeri görseli eklenebilir', () => {
    render(<FriendExperienceEditor onSave={onSave} />);

    fireEvent.click(screen.getByText('+ Görsel Ekle'));
    const imageInputs = screen.getAllByPlaceholderText('Görsel URL');
    expect(imageInputs).toHaveLength(1);

    fireEvent.change(imageInputs[0], { target: { value: '/images/test.jpg' } });
    fireEvent.click(screen.getByText('Kaydet'));

    const saved = onSave.mock.calls[0][0] as ContentItem;
    const trContent = saved.content.tr as FriendExperienceContent;
    expect(trContent.gallery).toEqual(['/images/test.jpg']);
  });

  it('lokasyon yorumu eklenebilir', () => {
    render(<FriendExperienceEditor onSave={onSave} />);

    fireEvent.click(screen.getByText('+ Yorum Ekle'));
    const nameInputs = screen.getAllByPlaceholderText('Yer Adı');
    const commentInputs = screen.getAllByPlaceholderText('Yorum');

    fireEvent.change(nameInputs[0], { target: { value: 'Sultanahmet' } });
    fireEvent.change(commentInputs[0], { target: { value: 'Harika bir yer' } });
    fireEvent.click(screen.getByText('Kaydet'));

    const saved = onSave.mock.calls[0][0] as ContentItem;
    const trContent = saved.content.tr as FriendExperienceContent;
    expect(trContent.locationComments).toHaveLength(1);
    expect(trContent.locationComments[0].locationName).toBe('Sultanahmet');
    expect(trContent.locationComments[0].comment).toBe('Harika bir yer');
  });
});
